language: node_js
node_js:
  - "10"
  - "12"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - export TZ=Europe/Berlin
before_script:
  - yarn add react react-dom
script:
  - yarn test:coverage
